spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        show_sql: ${HIBERNATE_SHOW_SQL:true}
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
  application:
    name: stickerstore
  datasource:
    password: ${DATABASE_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:stickerstore}?createDatabaseIfNotExist=true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /stickerstore/actuator
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    contact:
      name: Tuan Tran Pham
      github: https://github.com/tuantranpham204
